♻️ Per-1506 | Remove localizedSuffix if number is not compact
mitsinsar/CompactFormatter pull request #6
Opened 2022-10-18 16:17 UTC by onuralpavci

Since we were including `addSuffix(THOUSAND, LocalizedSuffix("B", "Bin"))` in `TurkishLocale` it causes a bug during formatting. For Thousand number, we are not compacting number but still add end suffix.

An easy solution could be to just remove that suffix from `TurkishLocale` but instead I wanted to control it as paramter, in case we want to compact thousands in the future. What do you think @mitsinsar ? If you accept the current solution, I also need to add `addSuffix(THOUSAND` for all other locales to avoid future bugs. Where can I find correct suffixes for other locales?

P.S. I also merged `implement-new-localizations` branch to this one as I could not find a branch which was up to date. If there is one I can change my base branch to that 🙏

2022-10-21 09:22 UTC, mitsinsar commented
Purpose of making `addSuffixes` function's return list optional is to make it as open as possible. There may be cases where we may want to shorten middle numbers but keep edges. 
If there is a suffix, it adds it. So, instead of adding a parameter, let's remove/comment out suffix from the list.

2022-10-21 09:23 UTC, mitsinsar requested changes
Purpose of making addSuffixes function's return list optional is to make it as open as possible. There may be cases where we may want to shorten middle numbers but keep edges. We can also change suffix'ed numbers based on localization in this way. Unnecessary, but we can :) 
If there is a suffix, it adds it. So, instead of adding a parameter, let's remove/comment out suffix from the list.

2022-10-25 13:28 UTC, onuralpavci commented
@mitsinsar I can see your point to make it as open as possible, but I think there should not be a case where the number is not compact but it has suffix at the end. Maybe I cannot think of an example but I don't think we would need such a case. Right now we provide flexibility for which range of numbers will have a suffix, but also we hardcoded that all numbers after million will be compact -> 
`val numberToFormat = if (rawNumber < NumberConstants.MILLION.value) rawNumber else this.parsedNumber`
I think it should be either compact and have suffix or it should What do you think?

Btw, @miracozkan will also open a PR on this library because he has a case where we need to make thousands compact too. Probably his implementation will fix this ticket too, so we can close this PR afterwards.

2022-10-25 15:23 UTC, mitsinsar commented
I agree with you, I missed that case @onuralpavci. We shouldn't let non-compact number to have suffix. Good point. As far as I understand, Mirac's solution solves this issue as well, as you said. After making sure that it solves this issue, we can close this one.

2022-10-26 13:23 UTC, closed without merging